-- Create the existing official-location shape for fresh databases. Existing
-- H2/PostgreSQL locations tables are preserved by IF NOT EXISTS.
CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(255) NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'STUDENT')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE location_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(20) NOT NULL CHECK (kind IN ('ADD', 'UPDATE')),
    existing_location_id BIGINT,
    location_name VARCHAR(255) NOT NULL,
    location_type VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    review_notes VARCHAR(500),
    submitted_by_user_id BIGINT NOT NULL,
    reviewed_by_user_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_suggestion_existing_location FOREIGN KEY (existing_location_id)
        REFERENCES locations(id) ON DELETE SET NULL,
    CONSTRAINT fk_suggestion_submitter FOREIGN KEY (submitted_by_user_id)
        REFERENCES user_accounts(id),
    CONSTRAINT fk_suggestion_reviewer FOREIGN KEY (reviewed_by_user_id)
        REFERENCES user_accounts(id)
);

CREATE INDEX idx_suggestions_submitter_created
    ON location_suggestions (submitted_by_user_id, created_at);
CREATE INDEX idx_suggestions_status_created
    ON location_suggestions (status, created_at);
